from pandas import NA


TRIP_COLUMN_TYPES = {
    # Identifiers
    'TripID':               'Int64',
    'DayID':                'Int64',
    'IndividualID':         'Int64',
    'HouseholdID':          'Int64',
    'PSUID':                'Int64',
    'PersNo':               'Int64',
    # Trip details
    'TravDay':              'Int64',
    'JourSeq':              'Int64',
    'HowComp_B01ID':        'Int64',
    'SeriesCall_B01ID':     'Int64',
    'ShortWalkTrip_B01ID':  'Int64',
    'NumStages':            'Int64',
    'NumStages_B01ID':      'Int64',
    # Mode
    'MainMode_B03ID':       'Int64',
    'MainMode_B04ID':       'Int64',
    'MainMode_B11ID':       'Int64',
    # Purpose
    'TripPurpFrom_B01ID':   'Int64',
    'TripPurpTo_B01ID':     'Int64',
    'TripPurpose_B01ID':    'Int64',
    'TripPurpose_B02ID':    'Int64',
    'TripPurpose_B04ID':    'Int64',
    # Start time
    'TripStartHours':       'Int64',
    'TripStartMinutes':     'Int64',
    'TripStart':            'Int64',
    'TripStart_B01ID':      'Int64',
    'TripStart_B02ID':      'Int64',
    # End time
    'TripEndHours':         'Int64',
    'TripEndMinutes':       'Int64',
    'TripEnd':              'Int64',
    'TripEnd_B01ID':        'Int64',
    'TripEnd_B02ID':        'Int64',
    # Distance
    'TripDisIncSW':         'float64',
    'TripDisIncSW_B01ID':   'Int64',
    'TripDisExSW':          'float64',
    'TripDisExSW_B01ID':    'Int64',
    # Time
    'TripTotalTime':        'Int64',
    'TripTotalTime_B01ID':  'Int64',
    'TripTravTime':         'float64',
    'TripTravTime_B01ID':   'Int64',
    # Geography
    'TripOrigGOR_B02ID':    'Int64',
    'TripDestGOR_B02ID':    'Int64',
    # Grossed up values
    'JJXSC':                'Int64',
    'JOTXSC':               'Int64',
    'JTTXSC':               'float64',
    'JD':                   'float64',
    # Weights
    'W5':                   'float64',
    'W5xHH':                'float64',
    # Survey year
    'SurveyYear':           'Int64',
}

DAY_COLUMN_TYPES = {
    # Identifiers
    'DayID':                        'Int64',
    'IndividualID':                 'Int64',
    'HouseholdID':                  'Int64',
    'PSUID':                        'Int64',
    'PersNo':                       'Int64',
    # Day details
    'TravDay':                      'Int64',
    'TravelYear':                   'Int64',
    'TravelWeekDay_B01ID':          'Int64',
    'TravelWeekDay_B02ID':          'Int64',
    'TravelWeekDay_B03ID':          'Int64',
    'TravelDayType_B01ID':          'Int64',
    'TravelDayTypeOld_B01ID':       'Int64',
    # Survey year
    'SurveyYear':                   'Int64',
}

INDIVIDUAL_COLUMN_TYPES = {
    # Identifiers
    'IndividualID':             'Int64',
    'HouseholdID':              'Int64',
    'PSUID':                    'Int64',
    'VehicleID':                'Int64',
    'PersNo':                   'Int64',
    # Interview and demographics
    'Interview_B01ID':          'Int64',
    'Age_B01ID':                'Int64',
    'Age_B04ID':                'Int64',
    'Sex_B01ID':                'Int64',
    'OfPenAge_B01ID':           'Int64',
    'HRPRelation_B01ID':        'Int64',
    'MarStat_B01ID':            'Int64',
    'LiveWith_B02ID':           'Int64',
    'EthGroupTS_B02ID':         'Int64',
    # Education
    'EdAttn1_B01ID':            'Int64',
    'EdAttn2_B01ID':            'Int64',
    'EdAttn3_B01ID':            'Int64',
    'EdAttn4_B02ID':            'Int64',
    'LeaHous_B01ID':            'Int64',
    'QLeaHous':                 'Int64',
    'NotLea_B01ID':             'Int64',
    'Educ_B01ID':               'Int64',
    'EducFT_B01ID':             'Int64',
    'EducN_B01ID':              'Int64',
    'HowSch_B01ID':             'Int64',
    # Travel frequency
    'OrdBusFreq_B01ID':         'Int64',
    'CoachFreq_B01ID':          'Int64',
    'TrainFreq_B01ID':          'Int64',
    'TaxiCabFreq_B01ID':        'Int64',
    'BicycleFreq_B01ID':        'Int64',
    'PlaneFreq_B01ID':          'Int64',
    'WalkFreq_B01ID':           'Int64',
    'OrdBus2Freq_B01ID':        'Int64',
    'Coach2Freq_B01ID':         'Int64',
    'Train2Freq_B01ID':         'Int64',
    'TaxiCab2Freq_B01ID':       'Int64',
    'Plane2Freq_B01ID':         'Int64',
    'Walk2Freq_B01ID':          'Int64',
    'Bicycle3Freq_B01ID':       'Int64',
    'PHVFreq_B01ID':            'Int64',
    'PHVFreq2_B01ID':           'Int64',
    'Bicycle2Freq_B01ID':       'Int64',
    # Walking
    'WhWalk_B01ID':             'Int64',
    'FarWalk':                  'Int64',
    'FarWalk_B01ID':            'Int64',
    'DistWalk':                 'Int64',
    'DistWalk_B01ID':           'Int64',
    'HTrWalk_B01ID':            'Int64',
    # Cycling
    'OwnCycle_B01ID':           'Int64',
    'Cycle12_B01ID':            'Int64',
    'CycRoute_B01ID':           'Int64',
    'CycMore_B01ID':            'Int64',
    'Cycle4w_B01ID':            'Int64',
    'ResMNCy_B01ID':            'Int64',
    'RsMnCyA_B01ID':            'Int64',
    'RsMnCyB_B01ID':            'Int64',
    'LeRidCy_B01ID':            'Int64',
    'YNCy2AM_B01ID':            'Int64',
    'YNCy2BM_B01ID':            'Int64',
    'YNCy2M_B01ID':             'Int64',
    'EncCycM_B01ID':            'Int64',
    'Ncyclane_B01ID':           'Int64',
    'Ebike_B01ID':              'Int64',
    'OwnCycleN_B01ID':          'Int64',
    'Bicycle2_B01ID':           'Int64',
    # Car and driving
    'CarPass_B01ID':            'Int64',
    'DrivLic_B02ID':            'Int64',
    'DrivExp_B01ID':            'Int64',
    'CarAccess_B01ID':          'Int64',
    'CarAccess_B02ID':          'Int64',
    'DrivDisable_B01ID':        'Int64',
    'LastDr_B01ID':             'Int64',
    'PDrivSt_B01ID':            'Int64',
    'DrivLik_B01ID':            'Int64',
    'ResNDrM_B01ID':            'Int64',
    'CarsEas_B01ID':            'Int64',
    'CAccIdnt_B01ID':           'Int64',
    'PrivCar_B01ID':            'Int64',
    'PrivCar2_B01ID':           'Int64',
    'CarWM_B01ID':              'Int64',
    'CarSM_B01ID':              'Int64',
    'WkLift_B01ID':             'Int64',
    # Public transport
    'PBlueBdg_B01ID':           'Int64',
    'EligPass_B01ID':           'Int64',
    'TicketHolding_B01ID':      'Int64',
    'NTrnsat_B01ID':            'Int64',
    'RelTrain_B01ID':           'Int64',
    'FrqTrain_B01ID':           'Int64',
    'NSatServ_B01ID':           'Int64',
    'NReliBus_B01ID':           'Int64',
    'NFrqBus_B01ID':            'Int64',
    'PHVuse_B01ID':             'Int64',
    # Work and employment
    'PrbJob_B01ID':             'Int64',
    'PrbNow_B01ID':             'Int64',
    'PrbSame_B01ID':            'Int64',
    'DTJbMonth_B01ID':          'Int64',
    'DTJbYear':                 'Int64',
    'DTJbLong_B01ID':           'Int64',
    'WkPlace_B01ID':            'Int64',
    'IndWkGOR_B02ID':           'Int64',
    'EcoStat_B02ID':            'Int64',
    'EcoStat_B03ID':            'Int64',
    'ES2000_B01ID':             'Int64',
    'ES2010_B01ID':             'Int64',
    'ES2020_B01ID':             'Int64',
    'NSSec_B03ID':              'Int64',
    'SC_B01ID':                 'Int64',
    'Stat_B01ID':               'Int64',
    'SVise_B01ID':              'Int64',
    'WkMode_B01ID':             'Int64',
    'ParkWk_B01ID':             'Int64',
    'OthWM_B01ID':              'Int64',
    'WkHome_B01ID':             'Int64',
    'PossHom_B01ID':            'Int64',
    'OftHome_B01ID':            'Int64',
    'PossTel_B01ID':            'Int64',
    'PossComp_B01ID':           'Int64',
    'TravSh_B01ID':             'Int64',
    'OthSM_B01ID':              'Int64',
    'WkMuch_B01ID':             'Int64',
    'PrbJobN_B01ID':            'Int64',
    'OCSect_B01ID':             'Int64',
    'OcPbSect_B01ID':           'Int64',
    # Disability and mobility
    'MobDiffSum_B01ID':         'Int64',
    'FootDiffSum_B01ID':        'Int64',
    'BusDiffSum_B01ID':         'Int64',
    'TravDiffSum_B01ID':        'Int64',
    'OthDis_B01ID':             'Int64',
    'PowWhl_B01ID':             'Int64',
    'PowWhUse_B01ID':           'Int64',
    'MobSct_B01ID':             'Int64',
    'MobScUse_B01ID':           'Int64',
    # School
    'SchDly_B01ID':             'Int64',
    'SchTrav_B01ID':            'Int64',
    'TravScW_B01ID':            'Int64',
    'SchAcc_B01ID':             'Int64',
    'SchAgeAcc':                'Int64',
    'PrivCar_B01ID':            'Int64',
    # Roads and safety
    'Roads_B01ID':              'Int64',
    'MainRd_B01ID':             'Int64',
    'Accident_B01ID':           'Int64',
    'Acc3Yr_B01ID':             'Int64',
    'Acc12Mn_B01ID':            'Int64',
    # Active travel
    'FootOut_B01ID':            'Int64',
    'BusOut_B01ID':             'Int64',
    'WalkProv_B01ID':           'Int64',
    'YNWkSAM_B01ID':            'Int64',
    'YNWkSBM_B01ID':            'Int64',
    'YNWkScM_B01ID':            'Int64',
    'EnWkScM_B01ID':            'Int64',
    'YNWlkAM_B01ID':            'Int64',
    'YNWlkBM_B01ID':            'Int64',
    'YNWlkM_B01ID':             'Int64',
    'EncWkM_B01ID':             'Int64',
    # Shopping and food
    'FdShp_B01ID':              'Int64',
    'FdDel_B01ID':              'Int64',
    'FdFreq_B01ID':             'Int64',
    'DelStrt_B01ID':            'Int64',
    'ShpEas_B01ID':             'Int64',
    'ShpTroN_B01ID':            'Int64',
    # Internet and phone
    'HomeIUse_B01ID':           'Int64',
    'OnGoIUse_B01ID':           'Int64',
    'ElseIUse_B01ID':           'Int64',
    'OwnPhone_B01ID':           'Int64',
    'SmPhUse_B01ID':            'Int64',
    'LackComp_B01ID':           'Int64',
    # Social
    'MarStN_B01ID':             'Int64',
    'ResNDnM_B01ID':            'Int64',
    'PossHmN_B01ID':            'Int64',
    'COB_B01ID':                'Int64',
    'MaritalS_B01ID':           'Int64',
    'ReNDNaM_B01ID':            'Int64',
    'ReNDNbM_B01ID':            'Int64',
    'MaritalStat_B01ID':        'Int64',
    'ResNDnM_B01ID':            'Int64',
    'GenHeal_B01ID':            'Int64',
    'PracNec_B01ID':            'Int64',
    'LivCit_B01ID':             'Int64',
    'LeftOut_B01ID':            'Int64',
    'Isolated_B01ID':           'Int64',
    'Lonely_B01ID':             'Int64',
    # Plane
    'IntPlane':                 'Int64',
    'IntPlane_B01ID':           'Int64',
    # Carer
    'Carer_B01ID':              'Int64',
    'Caretime_B01ID':           'Int64',
    # E-scooter
    'EScooter_B01ID':           'Int64',
    'EScooterFreq_B01ID':       'Int64',
    # Other
    'SRNRdSat_B01ID':           'Int64',
    'LocRdSat_B01ID':           'Int64',
    'SENo2_B01ID':              'Int64',
    'InterviewN_B01ID':         'Int64',
    # Survey year
    'SurveyYear':               'Int64',
}

TRIP_DAY_COLUMN_TYPES = {**TRIP_COLUMN_TYPES, **DAY_COLUMN_TYPES}

TRIP_DAY_INDIVIDUAL_COLUMN_TYPES = {**TRIP_DAY_COLUMN_TYPES, **INDIVIDUAL_COLUMN_TYPES}

MainMode_B04ID_map = {
    1: 'Walk',
    2: 'Pedal cycle',
    3: 'Car / van driver',
    4: 'Car / van passenger',
    5: 'Motorcycle',
    6: 'Other private transport',
    7: 'Bus in London',
    8: 'Other local bus',
    9: 'Non-local bus',
    10: 'London Underground',
    11: 'Surface Rail',
    12: 'Taxi / minicab',
    13: 'Other public transport',
    -8: 'NA',
    -10: 'DEAD'
}

OftHome_B01ID_map = {
    1: '3+ a week',
    2: '1 or 2 a week',
    3: '<1 a week, >2 a month',
    4: '1 or 2 a month',
    5: '<1 a month, >2 a year',
    6: '1 or 2 a year',
    7: '<1 a year or never',
    -8: 'NA',
    -9: 'DNA',
    -10: 'DEAD'
}

TripPurpose_B04ID_map = {
    1: 'Commuting',
    2: 'Business',
    3: 'Education / escort education',
    4: 'Shopping',
    5: 'Other escort',
    6: 'Personal business',
    7: 'Leisure',
    8: 'Other including just walk',
    -8: 'NA',
    -10: 'DEAD'
}

TravelWeekDay_B01ID_map = {
    1: 'Monday',
    2: 'Tuesday',
    3: 'Wednesday',
    4: 'Thursday',
    5: 'Friday',
    6: 'Saturday',
    7: 'Sunday',
    -10: 'DEAD'
}